authors:
  ioit-aaa:
    name: ioit-aaa
    description: ZhiZu.io CEO
    avatar: https://cdn.jsdelivr.net/gh/ioit-aaa/picx-images-hosting@master/20251001/20251001_19532571.4g4vd6txc9.png
    slug: ioit-aaa
    url: https://nry2025.xyz